#!/bin/sh

mkdir build
cd build

curl -L $1 -o dl.tar.gz
tar -zxvf dl.tar.gz

dir=`find . -name requirements.txt | sed 's/requirements.txt$//'`

if [ -z "$dir" ]; then
	echo "No requirements.txt"
	exit 1
fi

cd $dir

pip install -r requirements.txt
